version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-react-dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Prevent node_modules from being overwritten
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # Enable Vite HMR (Hot Module Replacement)
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge